apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: valkey-sentinel-ha
resources:
  - namespace.yaml
  - secret.yaml
  - services.yaml
  - configmap-valkey.yaml
  - statefulset-valkey.yaml
  - configmap-sentinel.yaml
  - statefulset-sentinel.yaml
