apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: valkey-cluster-ha
resources:
  - namespace.yaml
  - secret.yaml
  - services.yaml
  - configmap.yaml
  - statefulset.yaml
  - job-bootstrap.yaml
