apiVersion: v1
kind: Service
metadata:
  name: valkey-nodes
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: valkey-sentinel-ha
    app.kubernetes.io/component: valkey
  ports:
    - name: valkey
      port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: valkey-sentinel-peers
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: valkey-sentinel-ha
    app.kubernetes.io/component: sentinel
  ports:
    - name: sentinel
      port: 26379
      targetPort: 26379
---
apiVersion: v1
kind: Service
metadata:
  name: valkey-sentinel
spec:
  selector:
    app.kubernetes.io/name: valkey-sentinel-ha
    app.kubernetes.io/component: sentinel
  ports:
    - name: sentinel
      port: 26379
      targetPort: 26379
